# for local development
version: '3.9'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
    - '7000:8080'
    volumes:
    - '.:/vue_test'
    command: /bin/sh -c "npm run serve"